[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
bcrypt = "0.17.0"
rweb = "0.6"
sea-query = { version = "0.32.3", features = ["backend-postgres", "derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlite = "0.37.0"
tokio = "1"