CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Authors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    CONSTRAINT "PK_Authors" PRIMARY KEY ("Id")
);

CREATE TABLE "Genres" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Genres" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Username" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Username")
);

CREATE TABLE "Groups" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ParentId" text NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    CONSTRAINT "PK_Groups" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Groups_Users_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Users" ("Username") ON DELETE CASCADE
);

CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "AuthorId" integer NOT NULL,
    "GroupId" integer NOT NULL,
    "Rating" smallint NOT NULL,
    "IsFavorite" boolean NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Books_Authors_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Authors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Books_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BookGenre" (
    "BooksId" integer NOT NULL,
    "GenresId" integer NOT NULL,
    CONSTRAINT "PK_BookGenre" PRIMARY KEY ("BooksId", "GenresId"),
    CONSTRAINT "FK_BookGenre_Books_BooksId" FOREIGN KEY ("BooksId") REFERENCES "Books" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BookGenre_Genres_GenresId" FOREIGN KEY ("GenresId") REFERENCES "Genres" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_BookGenre_GenresId" ON "BookGenre" ("GenresId");

CREATE INDEX "IX_Books_AuthorId" ON "Books" ("AuthorId");

CREATE INDEX "IX_Books_GroupId" ON "Books" ("GroupId");

CREATE INDEX "IX_Groups_ParentId" ON "Groups" ("ParentId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250417202016_InitialCreate', '9.0.4');

DROP INDEX "IX_Books_GroupId";

ALTER TABLE "Users" ALTER COLUMN "LastName" TYPE character varying(50);

ALTER TABLE "Users" ALTER COLUMN "FirstName" TYPE character varying(50);

ALTER TABLE "Users" ALTER COLUMN "Username" TYPE character varying(50);

ALTER TABLE "Groups" ALTER COLUMN "ParentId" TYPE character varying(50);

ALTER TABLE "Groups" ALTER COLUMN "Name" TYPE character varying(50);

ALTER TABLE "Groups" ALTER COLUMN "Description" TYPE character varying(250);

ALTER TABLE "Genres" ALTER COLUMN "Name" TYPE character varying(50);

ALTER TABLE "Genres" ALTER COLUMN "Description" TYPE character varying(250);
ALTER TABLE "Genres" ALTER COLUMN "Description" DROP NOT NULL;

ALTER TABLE "Books" ALTER COLUMN "Title" TYPE character varying(50);

ALTER TABLE "Authors" ALTER COLUMN "LastName" TYPE character varying(50);

ALTER TABLE "Authors" ALTER COLUMN "FirstName" TYPE character varying(50);

CREATE UNIQUE INDEX "IX_Groups_Name_ParentId" ON "Groups" ("Name", "ParentId");

CREATE UNIQUE INDEX "IX_Books_GroupId_Title" ON "Books" ("GroupId", "Title");

CREATE UNIQUE INDEX "IX_Authors_FirstName_LastName" ON "Authors" ("FirstName", "LastName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250420003552_Migration1', '9.0.4');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250420003934_Migration2', '9.0.4');

COMMIT;

